### ISSUE TITLE
Can't run `npm start`

### ISSUE THREAD

**Issue by ollietreend** [matt3188/express-test#1]
Output when running `npm start`:

```
Ollies-MacBook-Pro:express-test ollietreend$ npm start

> node-test@0.0.0 start /Users/ollietreend/express-test
> node ./bin/www

module.js:341
    throw err;
    ^

Error: Cannot find module '/Users/ollietreend/express-test/bin/www'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.5.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.5.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! node-test@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-test@0.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-test
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-test
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ollietreend/express-test/npm-debug.log
```

**Comment by matt3188** [comment]
bin folder was not comited to repo, issue fixed
